# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50, unique=True)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_url', models.CharField(max_length=200)),
                ('resource_username', models.CharField(max_length=50)),
                ('resource_password', models.CharField(max_length=50)),
                ('env_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('resource_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Client')),
            ],
        ),
    ]
