# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('ORACLE', 'ORACLE'), ('MYSQL', 'MYSQL'), ('SQLSERVER', 'SQLSERVER'), ('DB2', 'DB2')], max_length=50),
        ),
    ]
