# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170708_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_query_app', models.CharField(max_length=50)),
                ('dict_query_name', models.CharField(max_length=50)),
                ('dict_key', models.CharField(max_length=50)),
                ('dict_value', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
