# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimerIntgFieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field_id', models.IntegerField()),
                ('from_field_name', models.CharField(max_length=50)),
                ('from_field_type', models.CharField(max_length=50)),
                ('from_field_length', models.IntegerField()),
                ('from_field_nullable', models.IntegerField()),
                ('to_field_id', models.IntegerField()),
                ('to_field_name', models.CharField(max_length=50)),
                ('to_field_type', models.CharField(max_length=50)),
                ('to_field_length', models.IntegerField()),
                ('to_field_nullable', models.IntegerField()),
                ('mapping_type', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timer_filed_mapping_t',
            },
        ),
        migrations.CreateModel(
            name='TimerIntgPerstep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perstep_conf', models.TextField()),
                ('perstep_type', models.CharField(max_length=50)),
                ('perstep_attribute', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timer_perstep_t',
            },
        ),
        migrations.CreateModel(
            name='TimerIntgPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_point_name', models.CharField(max_length=150)),
                ('integration_point_version', models.CharField(max_length=20)),
                ('env_name', models.CharField(max_length=50)),
                ('integration_point_status', models.IntegerField()),
                ('source_db_conn', models.CharField(max_length=100)),
                ('target_db_conn', models.CharField(max_length=100)),
                ('source_client_name', models.CharField(max_length=50)),
                ('target_client_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timer_integration_point_t',
            },
        ),
        migrations.CreateModel(
            name='TimerIntgStepRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_step_id', models.IntegerField()),
                ('to_step_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timer_step_relation_t',
            },
        ),
        migrations.AddField(
            model_name='timerintgperstep',
            name='intg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.TimerIntgPoint'),
        ),
    ]
