# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_intglist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intglist',
            unique_together=set([('integration_point_name', 'integration_point_version')]),
        ),
    ]
