# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_auto_20170718_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='from_field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='from_field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='from_field_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='from_field_nullable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='from_field_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='to_field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='to_field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='to_field_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='to_field_nullable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='to_field_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
