# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_auto_20171030_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='from_field_nullable',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timerintgfieldmapping',
            name='to_field_nullable',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='timerintgfieldmapping',
            table='timer_field_mapping_t',
        ),
    ]
