# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_auto_20171030_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerintgfieldmapping',
            name='from_field_length',
        ),
        migrations.RemoveField(
            model_name='timerintgfieldmapping',
            name='from_field_type',
        ),
        migrations.RemoveField(
            model_name='timerintgfieldmapping',
            name='to_field_length',
        ),
        migrations.RemoveField(
            model_name='timerintgfieldmapping',
            name='to_field_type',
        ),
    ]
