# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0007_remove_timerintgperstep_perstep_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('exclude_name', models.CharField(max_length=150)),
                ('exclude_from_time', models.DateTimeField()),
                ('exclude_end_time', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exclude_dispatch_t',
            },
        ),
    ]
