# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_excludedispatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcludeDispatch',
        ),
    ]
