# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartz', '0003_auto_20171111_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('task_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
