# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=50)),
                ('app_name', models.CharField(max_length=50)),
                ('app_owner', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField()),
                ('last_updated_by', models.CharField(max_length=30)),
                ('last_updated_date', models.DateTimeField()),
            ],
        ),
    ]
