# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appid',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appid',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
