# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0002_auto_20170625_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appid',
            name='app_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='appid',
            name='app_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
