# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0004_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_appid',
        ),
    ]
