# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0005_remove_projects_project_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_appid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appmanager.AppId'),
            preserve_default=False,
        ),
    ]
